### PR TITLE
Added Open in preview action

### PR DESCRIPTION
**Pull request by wczekalski**
I needed a way to view the diff in Preview (I needed to comare little details). Here's a little bit crude implementation but it works.

### CODE REVIEW

**Comment by orta** [comment]
would love a screenshot of new UI

**Comment by wczekalski** [comment]
screenshot at sty 21 16-32-43
There's no major difference

**Comment by wczekalski** [comment]
It should probably be something like "Open diff in Preview" will fix it.

**Comment by orta** [comment]
I'm alright with this :+1:

**Comment by orta** [comment]
Thanks of the PR

**Pull request merged**
